// Maths method is an intrinsic object that provide basic mathematics functionalities
// and constant

// Round is exactly like approximating a number
// We can use any of the 5 that is listed

// let x = 3.19; 
// x = Math.round(x)  
// x = Math.floor(x)   
// x = Math.ceil(x)     
// x = Math.pow(x, 2)    
// x = Math.sqrt(x)       
// x = Math.abs(x)
// console.log(x);

// let x = 3.19;
// let y = 5;
// let z = 9;

// maximum = Math.max(x, y, z);
// mini = Math.min(x, y, z);
// console.log(maximum);
// console.log(mini);

const resetBtn = document.querySelector('#resetBtn');
resetBtn.addEventListener('click', () => window.open('https://google.com'))